fix: improve exit handling of lake test and lake build scripts

diff --git a/.github/functional_tests/lake_test_failure/action.yml b/.github/functional_tests/lake_test_failure/action.yml
--- a/.github/functional_tests/lake_test_failure/action.yml
+++ b/.github/functional_tests/lake_test_failure/action.yml
@@ -35,6 +35,16 @@ runs:
       with:
         test: true
         use-github-cache: false
+
+  
+    - name: verify lean-action outcome
+      run: |
+        if [ "${{ steps.lean-action.outcome }}" != "failure" ]; then
+          echo "Expected lean-action outcome to be 'failure', but got '${{ steps.lean-action.outcome }}'"
+          exit 1
+        else
+          echo "lean-action outcome is ${{steps.lean-action.outcome}} as expected"
+        fi
       
     - name: verify lean-action outputs
       env:
